export const TERMINAL_WORLD_DATABASE_SCHEMA_VERSION = 1;

export const TERMINAL_WORLD_DATABASE_TABLE_ORDER = [
	'stories',
	'storyEntries',
	'entities',
	'entityAliases',
	'relationships',
	'factions',
	'factionMemberships',
	'factionResources',
	'factionGoals',
	'npcBeliefs',
	'agreements',
	'storyThreads',
	'storyEvents',
	'npcEventLinks',
	'statePatches',
	'memoryNodes',
	'chapters',
	'arcs',
	'backendJobs',
	'llmServiceSettings',
	'searchIndexRecords',
	'apiCallLogs',
] as const;

export const TERMINAL_WORLD_DATABASE_SCHEMA = {
	schemaVersion: TERMINAL_WORLD_DATABASE_SCHEMA_VERSION,
	name: 'Mtherios Terminal World Database',
	singleCanonRule: 'There is one application engine: the terminal core server. Browser clients, MCP clients, and Codex all call that engine; none of them own a separate canon path.',
	ownership: {
		engine: 'The terminal core server is the only runtime that assembles prompts, calls providers, validates patches, writes canon, schedules jobs, and updates search projections.',
		database: 'Postgres stores the authoritative world database. Every write path must land here through the terminal engine.',
		transcript: 'Transcript entries are evidence records. Structured records, events, patches, and memory nodes cite them through source refs.',
		wiki: 'Markdown/Obsidian is a generated readable projection over the database.',
		qdrant: 'Qdrant is a rebuildable semantic index over generated projections and retrieval text.',
		clients: 'Browser, phone, MCP, and Codex clients are control surfaces. They render, inspect, queue, and request work through terminal APIs.',
	},
	buildDatabase: {
		postgres: {
			description: 'Create the canonical database by applying the Drizzle migrations in order against Postgres.',
			commands: [
				'npm run backend:up',
				'npm run backend:migrate',
				'npm run app:database -- schema --out mtherios-world-schema.json',
			],
			migrationsDirectory: 'drizzle/',
			drizzleSchema: 'src/lib/server/db/schema.ts',
		},
		importBundle: {
			description: 'Create or restore a world database from a terminal world database JSON bundle.',
			commands: [
				'npm run app:database -- create --title "World name"',
				'npm run app:database -- import --file world-db.json',
			],
		},
	},
	importFormat: {
		rootKeys: ['schemaVersion', 'exportedAt', 'source', 'worldDatabase'],
		compatibilityRootKeys: ['backendCanon'],
		options: {
			preserveIds: 'Keep story/table ids from the source bundle. Defaults to true.',
			replaceExisting: 'Delete an existing story with the target id before import. Defaults to false.',
			syncWiki: 'Queue terminal wiki regeneration after import. Defaults to true.',
		},
		bundleJsonSchema: {
			type: 'object',
			required: ['schemaVersion', 'exportedAt', 'source', 'worldDatabase'],
			properties: {
				schemaVersion: { type: 'integer', minimum: 1 },
				exportedAt: { type: 'string', format: 'date-time' },
				source: { type: 'string' },
				worldDatabase: {
					type: 'object',
					required: ['story'],
					properties: {
						story: { type: 'object', description: 'Single story/world database shell.' },
						...Object.fromEntries(TERMINAL_WORLD_DATABASE_TABLE_ORDER
							.filter((name) => name !== 'stories')
							.map((name) => [name, { type: 'array', items: { type: 'object' } }])),
					},
					additionalProperties: true,
				},
			},
			additionalProperties: true,
		},
	},
	mcp: {
		serverName: 'mtherios',
		description: 'MCP exposes the same terminal engine APIs that the browser UI uses.',
		command: 'node',
		args: ['scripts/mtherios-mcp.mjs'],
		env: {
			MTHERIOS_APP_URL: 'http://127.0.0.1:5173',
		},
		codexConfigToml: [
			'[mcp_servers.mtherios]',
			"command = 'C:\\Program Files\\nodejs\\node.exe'",
			"args = ['E:\\DEV\\Projects\\mtherios-factions\\scripts\\mtherios-mcp.mjs']",
			'startup_timeout_sec = 120',
			'',
			'[mcp_servers.mtherios.env]',
			"MTHERIOS_APP_URL = 'http://127.0.0.1:5173'",
		].join('\n'),
		tools: [
			'mtherios_status',
			'mtherios_database_schema',
			'mtherios_list_databases',
			'mtherios_create_database',
			'mtherios_import_database',
			'mtherios_export_database',
			'mtherios_list_records',
			'mtherios_get_record',
			'mtherios_patch_record',
			'mtherios_search',
			'mtherios_run_turn',
			'mtherios_llm_settings',
			'mtherios_api_call_logs',
			'mtherios_jobs',
			'mtherios_reindex_story',
			'mtherios_sync_wiki',
		],
	},
	services: {
		createWorldDatabase: {
			method: 'POST',
			path: '/api/stories',
			description: 'Creates an empty terminal-owned world database/story shell.',
		},
		importWorldDatabase: {
			method: 'POST',
			path: '/api/database/import',
			description: 'Imports a full terminal world database bundle into Postgres.',
		},
		exportWorldDatabase: {
			method: 'GET',
			path: '/api/export/<storyId>',
			description: 'Exports a story as a terminal world database bundle plus compatibility fields.',
		},
		listWorldDatabases: {
			method: 'GET',
			path: '/api/stories',
			description: 'Lists terminal-owned world databases/stories.',
		},
		syncWikiProjection: {
			method: 'POST',
			path: '/api/app/jobs/wiki',
			description: 'Regenerates generated markdown/wiki and optionally Qdrant/lint projections from the database.',
		},
		listWorldRecords: {
			method: 'GET',
			path: '/api/stories/<storyId>/world?type=&q=&cursor=&limit=',
			description: 'Lists canonical world records by type with bounded pagination.',
		},
		getWorldRecord: {
			method: 'GET',
			path: '/api/records/<type>/<recordId>',
			description: 'Reads one canonical record with evidence, backlinks, and patch history where available.',
		},
		patchWorldRecord: {
			method: 'PATCH',
			path: '/api/records/<type>/<recordId>',
			description: 'Applies safe manual edits through the same patch/audit path as AI changes.',
		},
		searchWorldDatabase: {
			method: 'GET',
			path: '/api/stories/<storyId>/search?q=&type=&semantic=',
			description: 'Hybrid keyword/semantic search over canon and rebuildable Qdrant projections.',
		},
		runTurn: {
			method: 'POST',
			path: '/api/turn',
			description: 'Runs prompt assembly, model API calls, tool execution, state patch validation, and persistence in the terminal process.',
		},
		streamTurn: {
			method: 'POST',
			path: '/api/turn/stream',
			description: 'SSE wrapper over the same terminal turn engine.',
		},
		llmSettings: {
			method: 'GET/PATCH',
			path: '/api/settings/llm',
			description: 'Reads or updates terminal-side provider settings. Raw API keys stay outside Postgres and resolve through apiKeyRef.',
		},
		apiCallLogs: {
			method: 'GET',
			path: '/api/api-call-logs?storyId=&status=&serviceId=&limit=',
			description: 'Reads generation/provider/API timing and error logs recorded by the terminal engine.',
		},
	},
	tables: {
		stories: {
			purpose: 'One world database shell per story/campaign.',
			primaryKey: 'id',
			fields: ['id', 'clientStoryId', 'title', 'description', 'genre', 'mode', 'settings', 'headerPrompt', 'currentLocationId', 'currentTurn', 'currentWorldTime', 'metadata', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		storyEntries: {
			purpose: 'Transcript evidence: player actions, narration, system records, and imported source text.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'type', 'content', 'position', 'parentId', 'branchId', 'metadata', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		entities: {
			purpose: 'Characters, locations, items, faction entities, events, and concepts.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'type', 'name', 'description', 'status', 'visibility', 'state', 'metadata', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		entityAliases: {
			purpose: 'Alternate names and normalized lookup names for entities.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id', 'entityId -> entities.id'],
			fields: ['id', 'storyId', 'entityId', 'alias', 'normalizedAlias', 'sourceEntryIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		relationships: {
			purpose: 'Durable graph edges between entities: alliances, rivalries, kinship, ownership, location, debts, and other relationships.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id', 'sourceEntityId -> entities.id', 'targetEntityId -> entities.id'],
			fields: ['id', 'storyId', 'sourceEntityId', 'targetEntityId', 'type', 'label', 'strength', 'bidirectional', 'metadata', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		factions: {
			purpose: 'Faction-level records with pressure and compatibility projections for goals, resources, and members.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id', 'entityId -> entities.id'],
			fields: ['id', 'storyId', 'entityId', 'name', 'goals', 'resources', 'memberEntityIds', 'territoryIds', 'allies', 'enemies', 'pressure', 'metadata', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		factionMemberships: {
			purpose: 'Normalized membership edges from entities into factions.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id', 'factionId -> factions.id', 'entityId -> entities.id'],
			fields: ['id', 'storyId', 'factionId', 'entityId', 'role', 'rank', 'status', 'visibility', 'metadata', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		factionResources: {
			purpose: 'Normalized faction resources: armies, coin, spies, territory, supplies, influence, magic, and custom resources.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id', 'factionId -> factions.id'],
			fields: ['id', 'storyId', 'factionId', 'kind', 'name', 'amount', 'status', 'locationId', 'visibility', 'metadata', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		factionGoals: {
			purpose: 'Normalized public/secret faction objectives.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id', 'factionId -> factions.id'],
			fields: ['id', 'storyId', 'factionId', 'goal', 'status', 'priority', 'secrecy', 'metadata', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		npcBeliefs: {
			purpose: 'What a character believes about an entity or situation, including confidence and visibility.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id', 'believerEntityId -> entities.id'],
			fields: ['id', 'storyId', 'believerEntityId', 'subjectEntityId', 'belief', 'confidence', 'visibility', 'evidenceEventIds', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		agreements: {
			purpose: 'Treaties, oaths, debts, contracts, promises, pacts, bargains, and other commitments.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'parties', 'category', 'terms', 'status', 'secrecy', 'consequences', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		storyThreads: {
			purpose: 'Open and closed plot threads, unresolved questions, threats, schemes, and story agenda items.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'description', 'status', 'significance', 'relatedFactionIds', 'relatedEntityIds', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'closedAt', 'closureReason', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		storyEvents: {
			purpose: 'Canonical events and consequences produced by turns, imports, world simulation, and validated state changes.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'type', 'status', 'title', 'body', 'actorEntityIds', 'targetEntityIds', 'locationId', 'locationIds', 'factionIds', 'threadIds', 'visibility', 'createdTurn', 'occurredTurn', 'scheduledTurn', 'worldTime', 'memoryImpact', 'sourceEntryIds', 'sourcePatchIds', 'metadata', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		npcEventLinks: {
			purpose: 'Evidence-backed links between canonical timeline events and NPC memory/personality state.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id', 'eventId -> storyEvents.id', 'npcEntityId -> entities.id'],
			fields: ['id', 'storyId', 'eventId', 'npcEntityId', 'role', 'visibility', 'evidenceStrength', 'sourceEntryIds', 'sourcePatchIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		statePatches: {
			purpose: 'Proposed/applied structured changes from tools, imports, and narration validation.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'operations', 'reason', 'status', 'validationWarnings', 'sourceEntryIds', 'sourceEventIds', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		memoryNodes: {
			purpose: 'Retrieval memory and compiled world knowledge. Embeddings are optional local indexes, not the source of truth.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'type', 'title', 'content', 'summary', 'keywords', 'entityIds', 'factionIds', 'threadIds', 'locationId', 'visibility', 'importance', 'sourceEntryIds', 'sourceEventIds', 'sourcePatchIds', 'embedding', 'metadata', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		chapters: {
			purpose: 'Checkpoint summaries and durable scene rollups.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'number', 'title', 'sceneOutcome', 'irreversibleChanges', 'npcKnowledgeChanges', 'promisesDebtsOaths', 'discoveredClues', 'relationshipChanges', 'factionChanges', 'openThreads', 'sourceEntryIds', 'sourceEventIds', 'metadata', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		arcs: {
			purpose: 'Multi-chapter arc rollups.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'number', 'title', 'summary', 'chapterIds', 'sourceEventIds', 'openThreadIds', 'metadata', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		sagas: {
			purpose: 'Multi-arc saga rollups used as the highest compact narrative memory layer.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'number', 'title', 'summary', 'arcIds', 'keyFactionShifts', 'majorPowerChanges', 'lingeringThreads', 'overallTone', 'sourceEventIds', 'openThreadIds', 'metadata', 'serverVersion', 'createdAt', 'updatedAt'],
		},
		backendJobs: {
			purpose: 'Terminal job queue for embedding, reindex, chapter, arc, world-sim, scheme, strategic-world, and wiki projection work.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'type', 'status', 'priority', 'runAfter', 'attempts', 'maxAttempts', 'payload', 'result', 'lastError', 'metadata', 'createdAt', 'updatedAt', 'lockedAt', 'lockedBy', 'completedAt'],
		},
		llmServiceSettings: {
			purpose: 'Terminal-side LLM provider settings by service. Raw API keys are not stored; apiKeyRef resolves to env/config.',
			primaryKey: 'serviceId',
			fields: ['serviceId', 'providerType', 'baseUrl', 'model', 'temperature', 'maxTokens', 'topP', 'frequencyPenalty', 'presencePenalty', 'reasoningEffort', 'contextBudget', 'enabled', 'systemPromptOverride', 'apiKeyRef', 'metadata', 'createdAt', 'updatedAt'],
		},
		searchIndexRecords: {
			purpose: 'Qdrant/embedding index bookkeeping for canonical records and generated wiki pages. Rebuildable, never canon.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'recordType', 'recordId', 'pointId', 'collection', 'contentHash', 'model', 'status', 'error', 'sourceRefs', 'payload', 'metadata', 'indexedAt', 'createdAt', 'updatedAt'],
		},
		apiCallLogs: {
			purpose: 'Provider/API timing, model, token, and error diagnostics for terminal engine work.',
			primaryKey: 'id',
			foreignKeys: ['storyId -> stories.id'],
			fields: ['id', 'storyId', 'serviceId', 'operation', 'providerType', 'providerName', 'profileId', 'model', 'endpoint', 'status', 'durationMs', 'requestTokens', 'responseTokens', 'totalTokens', 'promptChars', 'responseChars', 'error', 'metadata', 'createdAt'],
		},
	},
} as const;
