import { and, eq, inArray, lte } from 'drizzle-orm';
import { getDb } from '$lib/server/db/client';
import {
	continuityWarnings,
	factionProjects,
	factionResources,
	factions,
	patchProposals,
	sourceRefs,
	stories,
} from '$lib/server/db/schema';

type Db = ReturnType<typeof getDb>;
type FactionProjectRow = typeof factionProjects.$inferSelect;
type FactionResourceRow = typeof factionResources.$inferSelect;

function nowIso(): string {
	return new Date().toISOString();
}

function asRecord(value: unknown): Record<string, unknown> {
	return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

function asStringArray(value: unknown): string[] {
	return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : [];
}

function normalizedKey(value: string): string {
	return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

function stableSuffix(value: string): string {
	return value.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').slice(0, 96) || 'project';
}

function numericCosts(project: FactionProjectRow): Array<{ key: string; amount: number }> {
	return Object.entries(asRecord(project.costs))
		.map(([key, value]) => ({ key, amount: typeof value === 'number' && Number.isFinite(value) ? value : NaN }))
		.filter((item) => Number.isFinite(item.amount) && item.amount > 0);
}

function resourceForCost(resources: FactionResourceRow[], key: string): FactionResourceRow | null {
	const target = normalizedKey(key);
	return resources.find((resource) =>
		normalizedKey(resource.kind) === target || normalizedKey(resource.name) === target
	) ?? null;
}

function evaluateProjectCosts(project: FactionProjectRow, resources: FactionResourceRow[]): {
	ok: boolean;
	warnings: string[];
	costs: Array<{ key: string; required: number; available: number | null; resourceId: string | null }>;
} {
	const costs = numericCosts(project).map((cost) => {
		const resource = resourceForCost(resources, cost.key);
		const available = typeof resource?.amount === 'number' && Number.isFinite(resource.amount)
			? resource.amount
			: null;
		return {
			key: cost.key,
			required: cost.amount,
			available,
			resourceId: resource?.id ?? null,
		};
	});
	const warnings = costs
		.filter((cost) => cost.available === null || cost.available < cost.required)
		.map((cost) => cost.available === null
			? `Missing resource "${cost.key}" for due faction project.`
			: `Insufficient resource "${cost.key}" for due faction project: needs ${cost.required}, has ${cost.available}.`);
	return {
		ok: warnings.length === 0,
		warnings,
		costs,
	};
}

function sourceRefRows(input: {
	storyId: string;
	proposalId: string;
	project: FactionProjectRow;
	confidence: number;
	now: string;
}) {
	const row = (sourceType: string, sourceId: string) => ({
		id: `sourceref_due_project_${stableSuffix(input.proposalId)}_${stableSuffix(sourceType)}_${stableSuffix(sourceId)}`,
		storyId: input.storyId,
		sourceType,
		sourceId,
		targetTable: 'patch_proposals',
		targetRecordId: input.proposalId,
		targetRecordField: 'operations',
		sourceField: 'faction_projects',
		confidence: input.confidence,
		rationale: `Faction project "${input.project.project}" is due for audit.`,
		notes: 'Generated by proposal-first faction project due audit.',
		serverVersion: input.project.serverVersion,
		createdAt: input.now,
		updatedAt: input.now,
	});
	return [
		...asStringArray(input.project.sourceEventIds).map((id) => row('story_event', id)),
		...asStringArray(input.project.sourcePatchIds).map((id) => row('state_patch', id)),
		...asStringArray(input.project.sourceEntryIds).map((id) => row('story_entry', id)),
	];
}

export async function auditDueFactionProjects(input: {
	storyId: string;
	limit?: number;
	db?: Db;
}): Promise<{
	storyId: string;
	currentTurn: number;
	dueProjectCount: number;
	proposalCount: number;
	warningCount: number;
	proposalIds: string[];
	warningIds: string[];
}> {
	const db = input.db ?? getDb();
	const limit = Math.max(1, Math.min(100, Math.trunc(input.limit ?? 20)));
	const now = nowIso();
	const [story] = await db.select().from(stories).where(eq(stories.id, input.storyId)).limit(1);
	if (!story) throw new Error(`Story not found: ${input.storyId}`);
	const currentTurn = Math.max(0, Math.trunc(story.currentTurn ?? 0));
	const projects = await db
		.select()
		.from(factionProjects)
		.where(and(
			eq(factionProjects.storyId, input.storyId),
			inArray(factionProjects.status, ['planned', 'active']),
			lte(factionProjects.dueTurn, currentTurn),
		))
		.limit(limit);
	if (projects.length === 0) {
		return {
			storyId: input.storyId,
			currentTurn,
			dueProjectCount: 0,
			proposalCount: 0,
			warningCount: 0,
			proposalIds: [],
			warningIds: [],
		};
	}

	const factionIds = [...new Set(projects.map((project) => project.factionId))];
	const [factionRows, resourceRows] = await Promise.all([
		db.select().from(factions).where(and(eq(factions.storyId, input.storyId), inArray(factions.id, factionIds))),
		db.select().from(factionResources).where(and(eq(factionResources.storyId, input.storyId), inArray(factionResources.factionId, factionIds))),
	]);
	const factionNameById = new Map(factionRows.map((faction) => [faction.id, faction.name]));
	const resourcesByFaction = new Map<string, FactionResourceRow[]>();
	for (const resource of resourceRows) {
		const list = resourcesByFaction.get(resource.factionId) ?? [];
		list.push(resource);
		resourcesByFaction.set(resource.factionId, list);
	}

	const proposalRows: Array<typeof patchProposals.$inferInsert> = [];
	const warningRows: Array<typeof continuityWarnings.$inferInsert> = [];
	const refRows: Array<typeof sourceRefs.$inferInsert> = [];
	for (const project of projects) {
		const resources = resourcesByFaction.get(project.factionId) ?? [];
		const costCheck = evaluateProjectCosts(project, resources);
		const proposalId = `proposal_due_project_${stableSuffix(project.id)}`;
		const warningId = `warning_due_project_${stableSuffix(project.id)}`;
		const factionName = factionNameById.get(project.factionId) ?? project.factionId;
		const proposedStatus = costCheck.ok ? 'completed' : 'blocked';
		const confidence = costCheck.ok ? 0.78 : 0.62;
		const auditMetadata = {
			sourceType: 'due_faction_project_audit',
			projectId: project.id,
			project: project.project,
			projectStatus: project.status,
			factionId: project.factionId,
			factionName,
			progress: project.progress,
			priority: project.priority,
			visibility: project.visibility,
			worldTime: project.worldTime,
			dueTurn: project.dueTurn,
			currentTurn,
			costs: costCheck.costs,
			gains: asRecord(project.gains),
			risks: asStringArray(project.risks),
			sourceEntryIds: asStringArray(project.sourceEntryIds),
			sourceEventIds: asStringArray(project.sourceEventIds),
			sourcePatchIds: asStringArray(project.sourcePatchIds),
		};
		proposalRows.push({
			id: proposalId,
			storyId: input.storyId,
			proposalType: costCheck.ok ? 'faction_project_due_resolution' : 'faction_project_blocked_resolution',
			targetTable: 'faction_projects',
			targetRecordId: project.id,
			proposedBy: 'faction_project_auditor',
			operations: [
				{
					op: 'replace',
					path: `/faction_projects/${project.id}/status`,
					value: proposedStatus,
				},
				{
					op: 'add',
					path: '/story_events',
					value: {
						type: 'faction_move',
						status: 'proposed',
						title: `${factionName}: ${project.project}`,
						body: costCheck.ok
							? `Due faction project can resolve: ${project.project}.`
							: `Due faction project appears blocked by resource constraints: ${project.project}.`,
						factionIds: [project.factionId],
						visibility: project.visibility,
						createdTurn: currentTurn,
						sourcePatchIds: asStringArray(project.sourcePatchIds),
						metadata: auditMetadata,
					},
				},
			],
			reason: `Faction project "${project.project}" is due on turn ${project.dueTurn ?? currentTurn}.`,
			suggestion: costCheck.ok
				? 'Review and apply this proposal to resolve the due faction project and create a faction movement event.'
				: 'Review blocked resources before applying project consequences.',
			status: costCheck.ok ? 'pending' : 'needs_review',
			decision: null,
			validatedBy: null,
			affectedEntityIds: [],
			confidence,
			sourceEntryIds: asStringArray(project.sourceEntryIds),
			sourceEventIds: asStringArray(project.sourceEventIds),
			sourcePatchIds: asStringArray(project.sourcePatchIds),
			metadata: auditMetadata,
			serverVersion: project.serverVersion,
			createdAt: now,
			updatedAt: now,
		});
		refRows.push(...sourceRefRows({
			storyId: input.storyId,
			proposalId,
			project,
			confidence,
			now,
		}));
		if (!costCheck.ok) {
			warningRows.push({
				id: warningId,
				storyId: input.storyId,
				warningType: 'faction_project_resource_constraint',
				level: 'warning',
				title: `Due faction project may be blocked: ${project.project}`,
				status: 'open',
				details: costCheck.warnings.join(' '),
				entityIds: [],
				factionIds: [project.factionId],
				threadIds: [],
				actorIds: [],
				sourceEntryIds: asStringArray(project.sourceEntryIds),
				sourceEventIds: asStringArray(project.sourceEventIds),
				sourcePatchIds: asStringArray(project.sourcePatchIds),
				resolutionNotes: null,
				resolvedBy: null,
				resolvedAt: null,
				metadata: {
					sourceType: 'due_faction_project_audit',
					projectId: project.id,
					costs: costCheck.costs,
				},
				serverVersion: project.serverVersion,
				createdAt: now,
				updatedAt: now,
			});
		}
	}

	if (proposalRows.length > 0) await db.insert(patchProposals).values(proposalRows).onConflictDoNothing();
	if (warningRows.length > 0) await db.insert(continuityWarnings).values(warningRows).onConflictDoNothing();
	if (refRows.length > 0) await db.insert(sourceRefs).values(refRows).onConflictDoNothing();

	return {
		storyId: input.storyId,
		currentTurn,
		dueProjectCount: projects.length,
		proposalCount: proposalRows.length,
		warningCount: warningRows.length,
		proposalIds: proposalRows.map((row) => row.id),
		warningIds: warningRows.map((row) => row.id),
	};
}
